In [1]:
# setting the path to the toolbox
import sys
#sys.path.insert(1,'/home/raojinhui/gwtoolbox/gwtoolbox/')

# importing the needed module
import numpy as np
from astropy.cosmology import Planck18 as cosmos
from gwtoolbox.tools_earth import Tools
from gwtoolbox.tools_EMC import *
from gwtoolbox.EM_HE import *
import matplotlib.pyplot as plt

%matplotlib inline
pop_para=[100,10,1.4,0.2,1.1,2.5,0.1]

In [4]:
# Search for GRB
from gwtoolbox.HE_models import *
# parameter tuning!
pi=3.1415926
half_open_mean=5.*pi/180.
half_open_std=1.*pi/180.
lg_r_grb_mean=14.5
lg_r_grb_std=0.1
lgEgrb_mean=49.3
lgEgrb_std=0.5
nup0_mean=0.003
nup0_std=0.001
jet_Gamma_mean=250
jet_Gamma_std=30

Band_alpha=-1.1
Band_beta=-2.5
Band_s=2
t_smear_intrinsic=0.3

model_para=[half_open_mean,half_open_std, lg_r_grb_mean, lg_r_grb_std,lgEgrb_mean, lgEgrb_std,nup0_mean, nup0_std, jet_Gamma_mean, jet_Gamma_std]

detector_type='ligo'
event_type='nsns'
population='I'
rho_cri=8. #snr
cosmos=cosmos
new_theta=pop_para
T=24.*60.*3650 # 2 years,1 month=43829.1 min

HE_detector='Fermi_GBM'
signal_type='sGRB_p'

In [5]:
tool=Tools(detector_type=detector_type, event_type=event_type, population=population,cosmos=cosmos, new_theta=pop_para)

total=tool.total_number(time_obs=T, rho_cri=rho_cri) #rho_cri? SNR?
print("expected number is: %f" % total)
total_poisson=np.random.poisson(lam=total)
sensitivity = tool.sensitivity_curve()
print(total_poisson,type(total_poisson))

expected number is: 66.548414
65 <class 'int'>

In [6]:
sensitivity

[array([   5.    ,    5.0115,    5.0231, ..., 4977.    , 4988.5   ,
        5000.    ]),
 array([1.9997e-20, 1.9462e-20, 1.8942e-20, ..., 2.4524e-23, 2.4580e-23,
        2.4637e-23])]

In [7]:
#len(sensitivity[0].tolist())

In [8]:
max_events=100
numevents=min(total_poisson, max_events)

#events2=tool.list_params_df(time_obs=T, rho_cri=rho_cri, size=numevents,dtp=False)
#events=tool.list_params_df(time_obs=T, rho_cri=rho_cri, size=numevents,dtp=True)

#events=tool.list_with_errors_df(time_obs=T, rho_cri=rho_cri,size=numevents,dtp=False)
events=tool.list_with_errors_df(T, rho_cri, numevents,dtp=True)
# Giving orbital inclinatio angles to each event. the flag "dtp" should be True
#GWtools.list_with_iota(DF_all);

In [9]:
events

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,dtb
0,0.077857,364.980380,1.507712,1.300683,-0.025605,0.038928,0.088639,0.076467,0.000598,192.204496,0.026
1,0.046471,213.116230,1.685095,1.252778,-0.120547,0.023235,0.088782,0.066005,0.000180,110.101822,0.214
2,0.022410,100.989544,1.351276,1.642102,0.055921,0.011205,0.067722,0.082297,0.000126,51.333806,0.660
3,0.049335,226.714799,1.506030,1.322116,-0.039504,0.024667,0.080019,0.070247,0.000285,117.342847,0.167
4,0.030005,135.971378,1.481095,1.546712,-0.130108,0.015002,0.075064,0.078390,0.000093,69.481283,0.501
...,...,...,...,...,...,...,...,...,...,...,...
60,0.045202,207.111272,1.196028,1.305856,0.113983,0.022601,0.062789,0.068555,0.000166,106.911731,0.163
61,0.031829,144.432509,1.303872,1.726673,-0.020112,0.015915,0.066306,0.087807,0.000294,73.896989,0.467
62,0.042227,193.064489,1.704166,1.161193,-0.043350,0.021113,0.088746,0.060470,0.000303,99.467552,0.260
63,0.044609,204.304911,1.126758,1.296908,-0.026036,0.022304,0.059055,0.067973,0.000411,105.422449,0.160
64,0.042802,195.777095,1.166763,1.326700,0.179120,0.021401,0.060853,0.069194,0.000155,100.903127,0.185

In [10]:
tool.list_with_iota(events)

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,dtb,inc
0,0.077857,364.980380,1.507712,1.300683,-0.025605,0.038928,0.088639,0.076467,0.000598,192.204496,0.026,0.249420
1,0.046471,213.116230,1.685095,1.252778,-0.120547,0.023235,0.088782,0.066005,0.000180,110.101822,0.214,0.611917
2,0.022410,100.989544,1.351276,1.642102,0.055921,0.011205,0.067722,0.082297,0.000126,51.333806,0.660,1.454897
3,0.049335,226.714799,1.506030,1.322116,-0.039504,0.024667,0.080019,0.070247,0.000285,117.342847,0.167,0.829300
4,0.030005,135.971378,1.481095,1.546712,-0.130108,0.015002,0.075064,0.078390,0.000093,69.481283,0.501,1.015712
...,...,...,...,...,...,...,...,...,...,...,...,...
60,0.045202,207.111272,1.196028,1.305856,0.113983,0.022601,0.062789,0.068555,0.000166,106.911731,0.163,0.756966
61,0.031829,144.432509,1.303872,1.726673,-0.020112,0.015915,0.066306,0.087807,0.000294,73.896989,0.467,1.204280
62,0.042227,193.064489,1.704166,1.161193,-0.043350,0.021113,0.088746,0.060470,0.000303,99.467552,0.260,0.580375
63,0.044609,204.304911,1.126758,1.296908,-0.026036,0.022304,0.059055,0.067973,0.000411,105.422449,0.160,0.415679
64,0.042802,195.777095,1.166763,1.326700,0.179120,0.021401,0.060853,0.069194,0.000155,100.903127,0.185,0.426409

In [12]:
HEtools=High_Energy(event_type=event_type, signal_type=signal_type, detector=HE_detector,model_para=model_para,cosmos=cosmos)

In [13]:
HEtools

## the first df1(table1):

In [14]:
#temp=events[(events['inc']<=40.*pi/180.)&(events['z']<2)].copy()
#events_HE=HEtools.Search_EMC(temp, full=True, verbose=True);
events=HEtools.Search_EMC(events, full=True, verbose=True)

In [15]:
events

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,...,dtheta,r0,Egrb,nup0,detected,T90,F_max,t_max,Epeak,fluence
0,0.077857,364.980380,1.507712,1.300683,-0.025605,0.038928,0.088639,0.076467,0.000598,192.204496,...,0.083020,3.753476e+14,1.676651e+48,0.003202,False,0.0,0.0,0.0,0,0.0
1,0.046471,213.116230,1.685095,1.252778,-0.120547,0.023235,0.088782,0.066005,0.000180,110.101822,...,0.093379,3.813515e+14,2.236178e+48,0.002673,False,0.0,0.0,0.0,0,0.0
2,0.022410,100.989544,1.351276,1.642102,0.055921,0.011205,0.067722,0.082297,0.000126,51.333806,...,0.073002,3.276431e+14,6.927547e+48,0.002115,False,0.0,0.0,0.0,0,0.0
3,0.049335,226.714799,1.506030,1.322116,-0.039504,0.024667,0.080019,0.070247,0.000285,117.342847,...,0.084865,2.804971e+14,1.885846e+49,0.005102,False,0.0,0.0,0.0,0,0.0
4,0.030005,135.971378,1.481095,1.546712,-0.130108,0.015002,0.075064,0.078390,0.000093,69.481283,...,0.101664,2.410296e+14,1.550860e+49,0.003775,False,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,0.045202,207.111272,1.196028,1.305856,0.113983,0.022601,0.062789,0.068555,0.000166,106.911731,...,0.086229,4.264094e+14,1.022992e+49,0.003613,False,0.0,0.0,0.0,0,0.0
61,0.031829,144.432509,1.303872,1.726673,-0.020112,0.015915,0.066306,0.087807,0.000294,73.896989,...,0.088221,3.289065e+14,1.569187e+50,0.002151,False,0.0,0.0,0.0,0,0.0
62,0.042227,193.064489,1.704166,1.161193,-0.043350,0.021113,0.088746,0.060470,0.000303,99.467552,...,0.104984,2.903705e+14,2.154054e+49,0.003833,False,0.0,0.0,0.0,0,0.0
63,0.044609,204.304911,1.126758,1.296908,-0.026036,0.022304,0.059055,0.067973,0.000411,105.422449,...,0.100404,3.653941e+14,8.549723e+48,0.001994,False,0.0,0.0,0.0,0,0.0
64,0.042802,195.777095,1.166763,1.326700,0.179120,0.021401,0.060853,0.069194,0.000155,100.903127,...,0.100653,3.141807e+14,7.738977e+49,0.002371,False,0.0,0.0,0.0,0,0.0

In [22]:
# select source that t90<2s
events=events[events['T90']<2]
print(len(events))
# select source that detected and t90<2s
#events_HE_det=events[(events['detected']==True)&(events['T90']<2)]
print(len(events_all[events_all['detected']==True]))

65
0

## the second df2(table2):

In [18]:

ET_tools=Tools(detector_type='et', event_type=event_type, population=population,cosmos=cosmos, new_theta=pop_para)
tot=ET_tools.total_number(time_obs=T, rho_cri=0.) #rho_cri? SNR?
print("expected number is: %f" % tot)
tot_poisson=np.random.poisson(lam=tot)
numevents=numevents=min(tot_poisson, max_events)############################################

DF_all=ET_tools.list_params_df(time_obs=T, rho_cri=0., size=numevents,dtp=True)
ET_tools.list_with_iota(DF_all)

#HEtools=High_Energy(event_type=event_type, signal_type=signal_type, detector=HE_detector,model_para=model_para,cosmos=cosmos)
temp=DF_all[(DF_all['inc']<=40.*pi/180.)&(DF_all['z']<2)].copy()
events_all=HEtools.Search_EMC(temp, full=True, verbose=True);
#events_all=HEtools.Search_EMC(DF_all, full=True, verbose=True)

expected number is: 797311.967743

/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:465: RuntimeWarning: invalid value encountered in divide
  filtered_flux=filtered_flux*np.trapz(fluxes,t_afterGW)/np.trapz(filtered_flux, filtered_t_afterGW)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:118: RuntimeWarning: invalid value encountered in arccos
  thetaT=np.arccos(np.where(1-c/r0*T>=-1,1-c/r0*T, -1))
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:120: RuntimeWarning: invalid value encountered in sqrt
  sinthetaT=np.sqrt(1-costhetaT**2)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:107: RuntimeWarning: invalid value encountered in power
  return (nup/nup0)**(1+alphaB)*(1+(nup/nup0)**s)**((betaB-alphaB)/s)

In [19]:
DF_all

           z             D        m1        m2         χ  dtb       inc
0   1.291869   9312.358905  1.331215  1.446273 -0.180858  1.0  1.176615
1   1.214129   8626.426843  1.620654  1.529937 -0.028584  1.0  0.993975
2   0.531712   3142.993301  1.570372  1.479538  0.079841  1.0  1.155686
3   1.288288   9280.553492  1.142266  1.900547  0.009282  1.0  1.436742
4   0.795856   5129.415871  1.691220  1.407015 -0.045900  1.0  1.494126
..       ...           ...       ...       ...       ...  ...       ...
95  0.696908   4361.032147  1.446480  1.107414  0.029941  1.0  0.472242
96  1.983346  15762.881252  1.297391  1.544982 -0.164611  1.0  1.149426
97  1.215923   8642.149108  1.479821  1.221255  0.132746  1.0  1.231448
98  0.647526   3987.925694  1.523068  1.416656 -0.111635  1.0  1.264059
99  1.667195  12744.783986  1.435587  1.470586  0.052967  1.0  1.301785

[100 rows x 7 columns]

In [20]:
events_all

,z,D,m1,m2,χ,dtb,inc,Gamma,dtheta,r0,Egrb,nup0,detected,T90,F_max,t_max,Epeak,fluence
6,1.074158,7417.171738,1.551105,1.372539,0.058405,1.0,0.693573,295.683976,0.077776,3.066798e+14,1.917111e+49,0.001532,False,0,0,0,0,0
12,1.778635,13796.955271,1.576098,1.187436,-0.131031,1.0,0.439985,248.600213,0.086003,2.868431e+14,3.663364e+48,0.002780,False,0,0,0,0,0
24,1.352979,9858.132044,1.206616,1.223544,0.027126,1.0,0.274588,217.111640,0.053407,2.506287e+14,3.456306e+48,0.003067,False,0,0,0,0,0
29,1.174877,8283.848884,1.429717,1.159993,0.098550,1.0,0.418944,218.032272,0.105749,4.208403e+14,5.763939e+49,0.001306,False,0,0,0,0,0
42,1.396189,10247.351371,1.334065,1.519040,0.069975,1.0,0.680449,250.221700,0.048589,3.114311e+14,2.200345e+48,0.004770,False,0,0,0,0,0
50,1.150053,8068.553159,1.114776,1.363127,0.003876,1.0,0.646918,250.027840,0.058338,3.213368e+14,8.414943e+48,0.003069,False,0,0,0,0,0
58,1.233305,8794.717151,1.152299,1.370021,-0.215116,1.0,0.688302,259.855487,0.083501,2.897974e+14,7.740571e+49,0.004067,False,0,0,0,0,0
68,1.191575,8429.264525,1.591929,1.379232,0.019684,1.0,0.694814,276.049692,0.064577,3.361880e+14,3.348067e+49,0.004265,False,0,0,0,0,0
72,1.056868,7270.279778,1.806425,1.410472,-0.110575,1.0,0.561103,240.615776,0.069752,2.830081e+14,3.537257e+49,0.003975,False,0,0,0,0,0
81,0.582594,3508.759345,1.216934,1.581125,-0.012291,1.0,0.607048,231.495208,0.072471,2.708444e+14,2.238045e+49,0.003893,False,0,0,0,0,0
82,0.783115,5028.999518,1.560402,1.479403,-0.035422,1.0,0.447241,270.714752,0.098097,3.364047e+14,1.881616e+49,0.004545,False,0,0,0,0,0
84,1.406439,10340.071834,1.306399,1.298088,-0.131701,1.0,0.575259,199.503042,0.081480,2.644972e+14,1.436384e+49,0.004013,False,0,0,0,0,0
87,1.461173,10837.617605,1.417976,1.397292,-0.134683,1.0,0.156132,257.365121,0.111250,2.770947e+14,3.927150e+49,0.001442,False,0,0,0,0,0
91,1.618278,12287.308834,1.230371,1.293231,0.016722,1.0,0.441378,217.050894,0.044162,3.186137e+14,5.207303e+48,0.002719,False,0,0,0,0,0
92,0.437436,2489.927409,1.485520,1.653817,0.150116,1.0,0.631242,246.076141,0.109576,3.584574e+14,6.274657e+49,0.002133,False,0,0,0,0,0
94,0.490389,2852.648478,1.400155,1.446017,-0.006683,1.0,0.597523,237.402135,0.076527,3.640507e+14,5.801400e+48,0.002689,False,0,0,0,0,0
95,0.696908,4361.032147,1.446480,1.107414,0.029941,1.0,0.472242,273.105559,0.068213,2.605311e+14,6.220297e+49,0.002124,False,0,0,0,0,0

In [21]:
len(events_all[events_all['detected']==True])

0