In [1]:
# setting the path to the toolbox
import sys
#sys.path.insert(1,'/home/raojinhui/gwtoolbox/gwtoolbox/')

# importing the needed module
import numpy as np
from astropy.cosmology import Planck18 as cosmos
from gwtoolbox.tools_earth import Tools
from gwtoolbox.tools_EMC import *
from gwtoolbox.EM_HE import *
import matplotlib.pyplot as plt

%matplotlib inline
pop_para=[100,10,1.4,0.2,1.1,2.5,0.1]

In [2]:
# Search for GRB
from gwtoolbox.HE_models import *
# parameter tuning!
pi=3.1415926
half_open_mean=5.*pi/180.
half_open_std=1.*pi/180.
lg_r_grb_mean=14.5
lg_r_grb_std=0.1
lgEgrb_mean=49.3
lgEgrb_std=0.5
nup0_mean=0.003
nup0_std=0.001
jet_Gamma_mean=250
jet_Gamma_std=30

Band_alpha=-1.1
Band_beta=-2.5
Band_s=2
t_smear_intrinsic=0.3

model_para=[half_open_mean,half_open_std, lg_r_grb_mean, lg_r_grb_std,lgEgrb_mean, lgEgrb_std,nup0_mean, nup0_std, jet_Gamma_mean, jet_Gamma_std]

detector_type='et'
event_type='nsns'
population='I'
rho_cri=1e-3 #snr
cosmos=cosmos
new_theta=pop_para
T=24.*60.*365 # 2 years,1 month=43829.1 min

HE_detector='Fermi_GBM'
signal_type='sGRB_p'

In [3]:
tool=Tools(detector_type=detector_type, event_type=event_type, population=population,cosmos=cosmos, new_theta=pop_para)

total=tool.total_number(time_obs=T, rho_cri=rho_cri) #rho_cri? SNR?
print("expected number is: %f" % total)
total_poisson=np.random.poisson(lam=total)
sensitivity = tool.sensitivity_curve()
print(total_poisson,type(total_poisson))

expected number is: 79731.196774
79558 <class 'int'>

In [4]:
sensitivity

[array([1.0000000e+00, 1.0030759e+00, 1.0061612e+00, ..., 9.9387655e+03,
        9.9693357e+03, 1.0000000e+04]),
 array([3.4959517e-17, 3.5445436e-17, 3.5797734e-17, ..., 5.3888363e-24,
        5.4060171e-24, 5.4232613e-24])]

In [5]:
#len(sensitivity[0].tolist())

In [17]:
numevents=100
#events2=tool.list_params_df(time_obs=T, rho_cri=rho_cri, size=numevents,dtp=False)
#events=tool.list_params_df(time_obs=T, rho_cri=rho_cri, size=numevents,dtp=True)

#events=tool.list_with_errors_df(time_obs=T, rho_cri=rho_cri,size=numevents,dtp=False)
events=tool.list_with_errors_df(T, rho_cri, numevents,dtp=True)
# Giving orbital inclinatio angles to each event. the flag "dtp" should be True
#GWtools.list_with_iota(DF_all);

In [18]:
events

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,dtb
0,1.595672,12076.839571,1.177892,1.396230,0.062252,0.039126,0.028811,0.034151,0.000377,363.755525,1.0
1,1.575542,11889.933215,1.253161,1.669002,0.015046,0.038784,0.030789,0.041006,0.002012,359.633572,1.0
2,1.630161,12398.187324,1.459735,1.225598,0.150584,0.039713,0.035438,0.029754,0.000210,370.822398,1.0
3,0.265394,1392.588257,1.731721,1.602476,0.074307,0.016512,0.072061,0.066683,0.000063,98.770013,1.0
4,0.371153,2051.710790,1.337901,1.699766,-0.021414,0.018310,0.051956,0.066008,0.000124,118.495731,1.0
...,...,...,...,...,...,...,...,...,...,...,...
95,1.685323,12915.014619,1.615075,1.451097,-0.053849,0.040650,0.040931,0.036190,0.000277,382.136439,1.0
96,2.641596,22322.354346,1.155117,1.404287,0.053440,0.056907,0.032731,0.040933,0.000543,580.384459,1.0
97,0.566330,3390.891070,1.439841,1.413985,0.001332,0.021628,0.050078,0.049179,0.000356,156.155256,1.0
98,2.485873,20742.031163,1.346515,1.634184,-0.068105,0.054260,0.032451,0.040370,0.000313,547.836511,1.0
99,2.410939,19987.397254,1.624127,1.434350,0.116227,0.052986,0.064586,0.055459,0.000229,532.209540,1.0

In [19]:
tool.list_with_iota(events)

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,dtb,inc
0,1.595672,12076.839571,1.177892,1.396230,0.062252,0.039126,0.028811,0.034151,0.000377,363.755525,1.0,1.243898
1,1.575542,11889.933215,1.253161,1.669002,0.015046,0.038784,0.030789,0.041006,0.002012,359.633572,1.0,0.658976
2,1.630161,12398.187324,1.459735,1.225598,0.150584,0.039713,0.035438,0.029754,0.000210,370.822398,1.0,0.315017
3,0.265394,1392.588257,1.731721,1.602476,0.074307,0.016512,0.072061,0.066683,0.000063,98.770013,1.0,1.247956
4,0.371153,2051.710790,1.337901,1.699766,-0.021414,0.018310,0.051956,0.066008,0.000124,118.495731,1.0,0.871691
...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.685323,12915.014619,1.615075,1.451097,-0.053849,0.040650,0.040931,0.036190,0.000277,382.136439,1.0,0.127961
96,2.641596,22322.354346,1.155117,1.404287,0.053440,0.056907,0.032731,0.040933,0.000543,580.384459,1.0,1.561744
97,0.566330,3390.891070,1.439841,1.413985,0.001332,0.021628,0.050078,0.049179,0.000356,156.155256,1.0,1.321827
98,2.485873,20742.031163,1.346515,1.634184,-0.068105,0.054260,0.032451,0.040370,0.000313,547.836511,1.0,1.553257
99,2.410939,19987.397254,1.624127,1.434350,0.116227,0.052986,0.064586,0.055459,0.000229,532.209540,1.0,1.024625

In [20]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   z       100 non-null    float64
 1   D       100 non-null    float64
 2   m1      100 non-null    float64
 3   m2      100 non-null    float64
 4   χ       100 non-null    float64
 5   dz      100 non-null    float64
 6   dm1     100 non-null    float64
 7   dm2     100 non-null    float64
 8   dχ      100 non-null    float64
 9   dD      100 non-null    float64
 10  dtb     100 non-null    float64
 11  inc     100 non-null    float64
dtypes: float64(12)
memory usage: 9.5 KB

In [21]:
HEtools=High_Energy(event_type=event_type, signal_type=signal_type, detector=HE_detector,model_para=model_para,cosmos=cosmos)

In [22]:
HEtools

## the first df1(table1):

In [33]:
#temp=events[(events['inc']<=40.*pi/180.)&(events['z']<2)].copy()
#events_HE=HEtools.Search_EMC(temp, full=True, verbose=True);
events=HEtools.Search_EMC(events, full=True, verbose=True)

/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:118: RuntimeWarning: invalid value encountered in arccos
  thetaT=np.arccos(np.where(1-c/r0*T>=-1,1-c/r0*T, -1))
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:120: RuntimeWarning: invalid value encountered in sqrt
  sinthetaT=np.sqrt(1-costhetaT**2)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:107: RuntimeWarning: invalid value encountered in power
  return (nup/nup0)**(1+alphaB)*(1+(nup/nup0)**s)**((betaB-alphaB)/s)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:465: RuntimeWarning: invalid value encountered in divide
  filtered_flux=filtered_flux*np.trapz(fluxes,t_afterGW)/np.trapz(filtered_flux, filtered_t_afterGW)

In [34]:
events

,z,D,m1,m2,χ,dz,dm1,dm2,dχ,dD,...,dtheta,r0,Egrb,nup0,detected,T90,F_max,t_max,Epeak,fluence
0,1.595672,12076.839571,1.177892,1.396230,0.062252,0.039126,0.028811,0.034151,0.000377,363.755525,...,0.081610,3.275302e+14,4.232809e+49,0.005068,False,0,0,0,0,0
1,1.575542,11889.933215,1.253161,1.669002,0.015046,0.038784,0.030789,0.041006,0.002012,359.633572,...,0.073345,3.041017e+14,5.635572e+48,0.003617,False,0,0,0,0,0
2,1.630161,12398.187324,1.459735,1.225598,0.150584,0.039713,0.035438,0.029754,0.000210,370.822398,...,0.111560,2.920142e+14,2.497865e+49,0.003142,False,0,0,0,0,0
3,0.265394,1392.588257,1.731721,1.602476,0.074307,0.016512,0.072061,0.066683,0.000063,98.770013,...,0.081952,3.396814e+14,1.227543e+49,0.003125,False,0,0,0,0,0
4,0.371153,2051.710790,1.337901,1.699766,-0.021414,0.018310,0.051956,0.066008,0.000124,118.495731,...,0.087157,4.229493e+14,4.183977e+49,0.002078,False,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.685323,12915.014619,1.615075,1.451097,-0.053849,0.040650,0.040931,0.036190,0.000277,382.136439,...,0.106544,2.931892e+14,1.049839e+50,0.003038,False,0,0,0,0,0
96,2.641596,22322.354346,1.155117,1.404287,0.053440,0.056907,0.032731,0.040933,0.000543,580.384459,...,0.079092,4.144723e+14,1.643470e+50,0.002555,False,0,0,0,0,0
97,0.566330,3390.891070,1.439841,1.413985,0.001332,0.021628,0.050078,0.049179,0.000356,156.155256,...,0.089998,1.882091e+14,1.051415e+49,0.002414,False,0,0,0,0,0
98,2.485873,20742.031163,1.346515,1.634184,-0.068105,0.054260,0.032451,0.040370,0.000313,547.836511,...,0.104069,2.728333e+14,2.399912e+49,0.002326,False,0,0,0,0,0
99,2.410939,19987.397254,1.624127,1.434350,0.116227,0.052986,0.064586,0.055459,0.000229,532.209540,...,0.104499,4.379451e+14,1.688847e+49,0.002404,False,0,0,0,0,0

In [36]:
# select source that t90<2s
events=events[events['T90']<2]
print(len(events))
# select source that detected and t90<2s
#events_HE_det=events[(events['detected']==True)&(events['T90']<2)]

100

## the second df2(table2):

In [25]:

ET_tools=Tools(detector_type='et', event_type=event_type, population=population,cosmos=cosmos, new_theta=pop_para)
tot=ET_tools.total_number(time_obs=T, rho_cri=0.) #rho_cri? SNR?
print("expected number is: %f" % tot)
tot_poisson=np.random.poisson(lam=tot)
numevents=100############################################

DF_all=ET_tools.list_params_df(time_obs=T, rho_cri=0., size=numevents,dtp=True)
ET_tools.list_with_iota(DF_all)

#HEtools=High_Energy(event_type=event_type, signal_type=signal_type, detector=HE_detector,model_para=model_para,cosmos=cosmos)
temp=DF_all[(DF_all['inc']<=40.*pi/180.)&(DF_all['z']<2)].copy()
events_all=HEtools.Search_EMC(temp, full=True, verbose=True);
#events_all=HEtools.Search_EMC(DF_all, full=True, verbose=True)

expected number is: 79731.196774

/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:465: RuntimeWarning: invalid value encountered in divide
  filtered_flux=filtered_flux*np.trapz(fluxes,t_afterGW)/np.trapz(filtered_flux, filtered_t_afterGW)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:118: RuntimeWarning: invalid value encountered in arccos
  thetaT=np.arccos(np.where(1-c/r0*T>=-1,1-c/r0*T, -1))
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:120: RuntimeWarning: invalid value encountered in sqrt
  sinthetaT=np.sqrt(1-costhetaT**2)
/Users/rjh/miniconda3/lib/python3.8/site-packages/gwtoolbox/EM_HE.py:107: RuntimeWarning: invalid value encountered in power
  return (nup/nup0)**(1+alphaB)*(1+(nup/nup0)**s)**((betaB-alphaB)/s)

In [26]:
DF_all

           z             D        m1        m2         χ  dtb       inc
0   0.967915   6523.909817  1.409978  1.533019 -0.060419  1.0  0.210724
1   0.844245   5514.524970  1.361310  1.520872 -0.145160  1.0  1.486958
2   2.461106  20492.175230  1.351589  1.236805  0.038463  1.0  1.459876
3   1.604213  12156.284973  1.361329  1.373440 -0.093135  1.0  1.353704
4   0.773052   4949.992762  1.385002  1.387378  0.000650  1.0  1.372726
..       ...           ...       ...       ...       ...  ...       ...
95  1.007899   6857.412687  1.286612  1.503930  0.047014  1.0  1.010834
96  1.611126  12220.656763  1.383357  1.779087  0.037212  1.0  1.178211
97  0.970311   6543.803996  1.463533  1.643336 -0.035904  1.0  1.490688
98  1.461173  10837.617605  1.417976  1.397292 -0.134683  1.0  1.114003
99  1.441360  10657.041952  1.499829  1.695398  0.073982  1.0  1.171723

[100 rows x 7 columns]

In [27]:
events_all

,z,D,m1,m2,χ,dtb,inc,Gamma,dtheta,r0,Egrb,nup0,detected,T90,F_max,t_max,Epeak,fluence
0,0.967915,6523.909817,1.409978,1.533019,-0.060419,1.0,0.210724,280.222816,0.089278,3.490138e+14,3.592278e+49,0.003224,False,0,0,0,0,0
11,1.147326,8044.964161,1.547250,1.269285,-0.175501,1.0,0.397898,259.760558,0.081769,2.474893e+14,3.562154e+49,0.003110,False,0,0,0,0,0
12,1.742178,13451.265461,1.139680,1.423877,0.045244,1.0,0.308714,251.600522,0.097746,2.652435e+14,6.446042e+49,0.003504,False,0,0,0,0,0
14,0.702663,4404.981588,1.123036,1.473569,-0.053158,1.0,0.065643,271.481860,0.065570,2.829924e+14,4.062987e+49,0.003967,False,0,0,0,0,0
25,1.884124,14804.916785,1.205976,1.355542,0.143437,1.0,0.669828,239.868623,0.054378,2.921391e+14,2.827548e+49,0.003735,False,0,0,0,0,0
30,1.468542,10904.915617,1.720575,1.700253,0.051730,1.0,0.258954,268.846459,0.080776,2.849603e+14,1.050029e+49,0.003222,False,0,0,0,0,0
39,1.291869,9312.358905,1.331215,1.446273,-0.180858,1.0,0.485425,296.136642,0.079742,2.511401e+14,1.509556e+49,0.002679,False,0,0,0,0,0
40,1.797526,13976.629142,1.541372,1.490060,-0.066826,1.0,0.538178,262.325121,0.107879,2.738504e+14,9.400535e+48,0.001979,False,0,0,0,0,0
42,1.827343,14260.974671,1.566677,1.361241,0.162151,1.0,0.651122,218.629200,0.073984,3.287992e+14,2.762634e+49,0.003375,False,0,0,0,0,0
45,1.282153,9226.110269,1.446333,1.384097,-0.095427,1.0,0.554729,263.154993,0.083654,3.431765e+14,7.112516e+48,0.002969,False,0,0,0,0,0
56,0.904836,6004.724350,1.448378,1.645693,-0.030457,1.0,0.499144,247.956171,0.105555,4.205959e+14,3.609337e+49,0.002723,False,0,0,0,0,0
75,1.985873,15787.394382,1.502104,1.521640,0.003146,1.0,0.280317,263.900709,0.077751,2.314266e+14,2.615835e+49,0.002180,False,0,0,0,0,0
83,1.778635,13796.955271,1.576098,1.187436,-0.131031,1.0,0.639737,268.369157,0.092027,2.328901e+14,7.582789e+49,0.003389,False,0,0,0,0,0
90,0.617886,3767.530278,1.665994,1.276550,-0.063239,1.0,0.454224,294.187448,0.062935,2.003331e+14,2.229253e+49,0.002884,False,0,0,0,0,0

In [32]:
len(events_all[events_all['detected']==True])

0